name: Process Release
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name'
        required: true
      tag:
        description: 'Release tag'
        required: true
jobs:
  process-release:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Repository: ${{ github.event.inputs.repo }}"
          echo "Tag: ${{ github.event.inputs.tag }}"
