name: Print Subject URL
on:
  workflow_dispatch:
    inputs:
      subject_url:
        description: 'The subject URL from the GitHub notification'
        required: true
        type: string

jobs:
  print-url:
    runs-on: ubuntu-latest
    steps:
      - name: Print Subject URL
        run: echo "Received subject_url:" " ${{ github.event.inputs.subject_url }}"
