name: Analysis
on:
  repository_dispatch:
    types: [analysis]
  workflow_dispatch:
    inputs:
      subject_url:
        description: 'The subject URL from the GitHub notification'
        required: true
        type: string

jobs:
  vt-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Print Subject URL ${{ github.event.client_payload.subject_url || github.event.inputs.subject_url }}
        run: |
          SUBJECT_URLs="${{ github.event.client_payload.subject_url || github.event.inputs.subject_url }}"
          echo "Received subject_url: $SUBJECT_URLs"
          echo "SUBJECT_URLs=$SUBJECT_URLs" >> $GITHUB_ENV

      - name: Cache vt
        id: cache-vt
        uses: actions/cache@v4
        with:
          path: ~/vt
          key: vt-${{ runner.os }}-vt-1.3.0
          # restore-keys: vt-${{ runner.os }}-
    
      - name: Cache jq
        id: cache-jq
        uses: actions/cache@v4
        with:
          path: ~/jq
          key: jq-${{ runner.os }}-jq-1.8.1
  
      - name: Download and install vt
        if: steps.cache-vt.outputs.cache-hit != 'true'
        run: |
          curl -L -o vt.zip https://github.com/VirusTotal/vt-cli/releases/download/1.3.0/Linux64.zip
          echo "2d3d67c84e9cf43c50b6655af73f8df010e1185370059a0c9c72ff39dd33def4 vt.zip" | sha256sum -c
          unzip vt.zip
          chmod +x vt
          mv vt ~/vt
  
      - name: Download and install jq
        if: steps.cache-jq.outputs.cache-hit != 'true'
        run: |
          curl -L -o jq https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-linux-amd64
          echo "020468de7539ce70ef1bceaf7cde2e8c4f2ca6c3afb84642aabc5c97d9fc2a0d jq" | sha256sum -c
          chmod +x jq
          mv jq ~/jq

      # - name: Cache wget2 apt
      #   uses: actions/cache@v4
      #   id: cache-wget2
      #   with:
      #     path: /var/cache/apt/archives
      #     key: ${{ runner.os }}-apt-wget2

      # - name: Update and Download wget2
      #   if: steps.cache-wget2.outputs.cache-hit != 'true'
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y --download-only wget2

      # - name: Install wget2
      #   run: |
      #     sudo apt-get install -y wget2
  
      - name: Add GITHUB_PATH
        run: |
          echo "$HOME" >> "$GITHUB_PATH"
          mkdir -p /home/runner/.cache
  
      - name: init vt
        run: vt init -k ${{ secrets.VT_KEY }}

      - name: extract apk(s) urls
        id: find-apk-urls
        run: |
          # curl -sL $SUBJECT_URLs | jq -r .assets[].browser_download_url | grep -E '\.apks?$' | grep -v x86 > ~/urls.txt || echo "result=failure" >> $GITHUB_OUTPUT
          # cat ~/urls.txt || exit 0

          echo $SUBJECT_URLs
          DL_URLS=$(curl -sL $SUBJECT_URLs | jq -r '.assets[].browser_download_url')

          APKs=$(echo "$DL_URLS" | grep -iE '(arm64|v8a?|armv8a?).+\.apk$' || true)

          if [ -z "$APKs" ]; then
              APKs=$(echo "$DL_URLS" | grep -iE '\.apk$' || true)
          fi

          if [ -z "$APKs" ]; then
              APKs=$(echo "$DL_URLS" | grep -iE '\.apks$'|| true)
          fi

          if [ -z "$APKs" ]; then
              echo "No matching assets found."
              echo "skip=true" >> $GITHUB_OUTPUT
          fi

          echo "$APKs"
          echo "$APKs" > ~/urls.txt
          
      - name: vt scan urls
        id: scan-urls
        if: steps.find-apk-urls.outputs.skip != 'true'
        run: |
          cat ~/urls.txt
          # # cat ~/urls.txt | vt scan url - | cut -f 2 -d ' ' | vt analysis -
          # # while IFS= read -r url; do vt scan url "$url" | cut -f 2 -d ' ' | vt analysis -; done < ~/urls.txt
          # while IFS= read -r url; do vt scan url "$url" ; done < ~/urls.txt

          # cat ~/urls.txt | wget2 -i -
          curl -L --remote-name-all -Z $(cat ~/urls.txt)
          find . -maxdepth 1 \( -name '*.apk' -o  -name '*.apks' \) -exec vt scan file {} \+
          
      # - name: vt scan files
      #   if: steps.find-apk-urls.outputs.result != 'failure'
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #   run: |
      #     urls=$(cat ~/urls.txt)
      #     curl -L -Z --remote-name-all $urls
      #     vt scan file *.apk *.apks | cut -f 2 -d ' ' | vt analysis -
