name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: pwd
      run: pwd

    - name: Cache jq
      id: cache-jq
      uses: actions/cache@v4
      with:
        path: ~/jq
        key: jq-${{ runner.os }}-jq-1.7
        restore-keys: jq-${{ runner.os }}-

    - name: Download and install jq
      if: steps.cache-jq.outputs.cache-hit != 'true'
      run: |
        curl -L -o jq https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-linux-amd64
        echo "020468de7539ce70ef1bceaf7cde2e8c4f2ca6c3afb84642aabc5c97d9fc2a0d  jq" | sha256sum -c
        chmod +x jq
        #mkdir -p ~/.jq
        mv jq ~/jq

    - name: Run jq command
      run: |
        echo '{"test": "value"}' | ~/jq '.test'
