name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache jq
      id: cache-jq
      uses: actions/cache@v4
      with:
        path: ~/jq
        key: jq-${{ runner.os }}-jq-1.7
        restore-keys: jq-${{ runner.os }}-

    - name: Download and install jq
      if: steps.cache-jq.outputs.cache-hit != 'true'
      run: |
        curl -L -o jq https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux64
        echo "b3a00d65f753d325b0c6a1b528498de0fd747f5c6e8c86e5664d3b3b1c0c6b0a  jq" | sha256sum -c
        chmod +x jq
        //mkdir -p ~/.jq
        mv jq ~/jq

    - name: Run jq command
      run: |
        echo '{"test": "value"}' | ~/jq '.test'
